# Generated by Django 5.0.1 on 2024-02-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registereddata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.IntegerField()),
                ('passw', models.CharField(max_length=20)),
                ('passw1', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='registereddata',
        ),
    ]
